version: 2.1


orbs:
  python: circleci/python@1.5.0


jobs:
  tests:
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DATABASE_HOST: localhost
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command:
            python manage.py test -v 2


  heroku-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a lechomdu web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a lechomdu web
workflows:
  test-and-deploy:
    jobs:
      - tests
      - heroku-deploy:
          requires:
              - tests
