# Generated by Django 4.0.4 on 2022-05-10 12:12

from django.db import migrations, models


def upload_words(apps, schema_editor):
    Word = apps.get_model('game', 'Word')
    words = ["corbeau", "amoral", "admission", "humeur", "cadeau", "complice", "bouche",
             "ballet",
             "pictural", "infini", "messie", "regarder", "tragique", "bastion", "articulation",
             "sabotage", "philosophie", "condition", "oiseau", "compagnie", "pratique"]
    for word in words:
        Word.objects.create(word=word)
        print(f"Mot ajouté :{word}")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('word', models.CharField(max_length=12)),
            ],
        ),
        migrations.RunPython(upload_words)
    ]
