# Generated by Django 4.0.4 on 2022-05-30 16:11

from django.db import migrations, models


def upload_new_words(apps, schema_editor):
    Word = apps.get_model('game', 'Word')
    words = open('words.txt')
    words = words.read().split(" ")
    for word in words:
        Word.objects.get_or_create(word=word)
        print(f"Mot ajouté :{word}")


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upload_new_words)
    ]
