# Generated by Django 4.0.4 on 2022-05-31 21:35

from django.db import migrations, models


def delete_even_word_objects(apps, schema_editor):
    Word = apps.get_model('game', 'Word')
    words = Word.objects.all()
    for word in words:
        if word.id % 2 == 0:
            print(f"Mot supprimé :{word.word}")
            word.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0002_auto_20220530_1811'),
    ]

    operations = [
        migrations.RunPython(delete_even_word_objects)
    ]
