# Generated by Django 4.0.4 on 2022-05-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_streak',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='played_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='won_games',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
