# Generated by Django 4.0.4 on 2022-05-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_on_streak_user_played_games_user_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_on_streak',
        ),
    ]
