# Generated by Django 4.0.4 on 2022-05-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_badges_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
